(function(){
  const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rootPath=p=>String(p||'').replace(/^\//,'');
  const formatDate=s=>{const d=new Date(s+'T00:00:00');return isNaN(d)?s:`${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')}`};
  const instagramUrl=value=>{try{const u=new URL(String(value||'').trim());const host=u.hostname.toLowerCase().replace(/^www\./,'');if(!['instagram.com','instagr.am'].includes(host))return'';if(!/^\/(p|reel|tv)\/[^/]+\/?/.test(u.pathname))return'';return`https://www.instagram.com${u.pathname.endsWith('/')?u.pathname:u.pathname+'/'}`}catch(e){return''}};
  const loadInstagramEmbed=()=>{if(window.instgrm?.Embeds){window.instgrm.Embeds.process();return}if(document.querySelector('script[data-amona-instagram]'))return;const s=document.createElement('script');s.async=true;s.src='https://www.instagram.com/embed.js';s.dataset.amonaInstagram='true';document.body.appendChild(s)};
  const instagramBlock=value=>{const url=instagramUrl(value);if(!url)return'';return`<section class="article-instagram"><p class="instagram-heading">Instagram</p><blockquote class="instagram-media" data-instgrm-permalink="${escapeHtml(url)}" data-instgrm-version="14"></blockquote><a class="instagram-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">Instagramで見る →</a></section>`};
  const card=p=>`<a class="blog-card" href="blog-post.html?id=${encodeURIComponent(p.id)}"><img src="${escapeHtml(rootPath(p.image))}" alt="${escapeHtml(p.title)}"><div class="blog-card-body"><div class="blog-meta"><time>${formatDate(p.date)}</time><span class="blog-category">${escapeHtml(p.category)}</span></div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.summary||'')}</p></div></a>`;
  async function load(){const res=await fetch('blog-data.json?v='+Date.now());if(!res.ok)throw new Error('load failed');return(await res.json()).filter(p=>p.published!==false).sort((a,b)=>String(b.date).localeCompare(String(a.date)))}
  async function top(){const el=document.getElementById('topBlogGrid');if(!el)return;try{const posts=await load();el.innerHTML=posts.length?posts.slice(0,3).map(card).join(''):'<div class="blog-empty">現在、公開中の記事はありません。</div>'}catch(e){el.innerHTML='<div class="blog-empty">記事を表示できませんでした。</div>'}}
  async function list(){const el=document.getElementById('blogList');if(!el)return;const buttons=[...document.querySelectorAll('[data-blog-filter]')];try{const posts=await load();const draw=cat=>{const shown=cat==='すべて'?posts:posts.filter(p=>p.category===cat);el.innerHTML=shown.length?shown.map(card).join(''):'<div class="blog-empty">該当する記事はありません。</div>'};draw('すべて');buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.blogFilter)}))}catch(e){el.innerHTML='<div class="blog-empty">記事を表示できませんでした。</div>'}}
  async function detail(){const el=document.getElementById('blogArticle');if(!el)return;try{const posts=await load(),id=new URLSearchParams(location.search).get('id'),p=posts.find(x=>x.id===id)||posts[0];if(!p){el.innerHTML='<p>記事が見つかりません。</p>';return}document.title=p.title+'｜HAIRSALON amona';const instagram=instagramBlock(p.instagram_url);el.innerHTML=`<div class="article-meta"><time>${formatDate(p.date)}</time><span>${escapeHtml(p.category)}</span></div><h1>${escapeHtml(p.title)}</h1><img class="article-image" src="${escapeHtml(rootPath(p.image))}" alt="${escapeHtml(p.title)}"><div class="article-body">${escapeHtml(p.body||'').replace(/\n/g,'<br>')}</div>${instagram}`;if(instagram)loadInstagramEmbed()}catch(e){el.innerHTML='<p>記事を表示できませんでした。</p>'}}
  document.addEventListener('DOMContentLoaded',()=>{top();list();detail()});
})();
